name: lilac
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- absl-py=1.0.0
- aiohttp=3.7.4.post0
- asttokens=2.0.5
- async-timeout=3.0.1
- attrs=21.4.0
- backcall=0.2.0
- backports=1.0
- backports.functools_lru_cache=1.6.4
- blas=1.0
- blinker=1.4
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2021.10.8
- cachetools=5.0.0
- certifi=2021.10.8
- cffi=1.15.0
- chardet=4.0.0
- charset-normalizer=2.0.4
- click=8.0.4
- colorama=0.4.4
- cryptography=36.0.0
- cudatoolkit=11.3.1
- decorator=5.1.1
- executing=0.8.3
- ffmpeg=4.3
- freetype=2.11.0
- fsspec=2022.2.0
- future=0.18.2
- giflib=5.2.1
- gmp=6.2.1
- gnutls=3.6.15
- google-auth=2.6.2
- google-auth-oauthlib=0.4.6
- grpcio=1.42.0
- idna=3.3
- importlib-metadata=4.11.3
- intel-openmp=2021.4.0
- ipython=8.1.1
- jedi=0.18.1
- jpeg=9d
- lame=3.100
- lcms2=2.12
- ld_impl_linux-64=2.35.1
- libffi=3.3
- libgcc-ng=9.3.0
- libgomp=9.3.0
- libiconv=1.15
- libidn2=2.3.2
- libpng=1.6.37
- libprotobuf=3.15.8
- libstdcxx-ng=9.3.0
- libtasn1=4.16.0
- libtiff=4.2.0
- libunistring=0.9.10
- libuv=1.40.0
- libwebp=1.2.2
- libwebp-base=1.2.2
- lz4-c=1.9.3
- markdown=3.3.6
- matplotlib-inline=0.1.3
- mkl=2021.4.0
- mkl-service=2.4.0
- mkl_fft=1.3.1
- mkl_random=1.2.2
- multidict=5.2.0
- ncurses=6.3
- nettle=3.7.3
- numpy=1.21.2
- numpy-base=1.21.2
- oauthlib=3.2.0
- openh264=2.1.1
- openssl=1.1.1n
- packaging=21.3
- parso=0.8.3
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=9.0.1
- pip=21.2.4
- prompt-toolkit=3.0.27
- protobuf=3.15.8
- ptyprocess=0.7.0
- pure_eval=0.2.2
- pyasn1=0.4.8
- pyasn1-modules=0.2.7
- pycparser=2.21
- pydeprecate=0.3.2
- pygments=2.11.2
- pyjwt=2.3.0
- pyopenssl=22.0.0
- pyparsing=3.0.7
- pysocks=1.7.1
- python=3.8.12
- python_abi=3.8
- pytorch=1.11.0
- pytorch-lightning=1.5.10
- pytorch-mutex=1.0
- pyu2f=0.1.5
- pyyaml=5.4.1
- readline=8.1.2
- requests=2.27.1
- requests-oauthlib=1.3.1
- rsa=4.8
- setuptools=58.0.4
- six=1.16.0
- sqlite=3.38.0
- stack_data=0.2.0
- tensorboard=2.8.0
- tensorboard-data-server=0.6.0
- tensorboard-plugin-wit=1.8.1
- tk=8.6.11
- torchaudio=0.11.0
- torchmetrics=0.7.2
- torchvision=0.12.0
- tqdm=4.63.0
- traitlets=5.1.1
- typing-extensions=4.1.1
- typing_extensions=4.1.1
- urllib3=1.26.8
- wcwidth=0.2.5
- werkzeug=2.0.3
- wheel=0.37.1
- xz=5.2.5
- yaml=0.2.5
- yarl=1.6.3
- zipp=3.7.0
- zlib=1.2.11
- zstd=1.4.9
- pip:
  - antlr4-python3-runtime==4.8
  - black==22.1.0
  - cfgv==3.3.1
  - cycler==0.11.0
  - distlib==0.3.4
  - docker-pycreds==0.4.0
  - filelock==3.6.0
  - flake8==4.0.1
  - fonttools==4.31.2
  - gitdb==4.0.9
  - gitpython==3.1.27
  - hydra-core==1.1.1
  - identify==2.4.12
  - importlib-resources==5.4.0
  - isort==5.10.1
  - kiwisolver==1.4.0
  - matplotlib==3.5.1
  - mccabe==0.6.1
  - mypy-extensions==0.4.3
  - nodeenv==1.6.0
  - omegaconf==2.1.1
  - pathspec==0.9.0
  - pathtools==0.1.2
  - platformdirs==2.5.1
  - pre-commit==2.17.0
  - promise==2.3
  - psutil==5.9.0
  - pycodestyle==2.8.0
  - pyflakes==2.4.0
  - python-dateutil==2.8.2
  - sentry-sdk==1.5.8
  - setproctitle==1.2.2
  - shortuuid==1.0.8
  - smmap==5.0.0
  - termcolor==1.1.0
  - toml==0.10.2
  - tomli==2.0.1
  - virtualenv==20.13.4
  - wandb==0.12.11
  - yaspin==2.1.0
